// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQB6FFtQgNepkkuXFTDrHN4oazvpmTa88',
    appId: '1:861039145649:web:9525720fa53cf1637da890',
    messagingSenderId: '861039145649',
    projectId: 'santefamille-c95e3',
    authDomain: 'santefamille-c95e3.firebaseapp.com',
    storageBucket: 'santefamille-c95e3.firebasestorage.app',
    measurementId: 'G-D348GFNFQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBie7b5l6qVohtxxHz7tHAo8YXx7fQVwUI',
    appId: '1:861039145649:android:052da8f405447ee27da890',
    messagingSenderId: '861039145649',
    projectId: 'santefamille-c95e3',
    storageBucket: 'santefamille-c95e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClaOs2uPoOUREbK2H-1h7Ki6TAFIuHItc',
    appId: '1:861039145649:ios:d68facf4dfb3c1d07da890',
    messagingSenderId: '861039145649',
    projectId: 'santefamille-c95e3',
    storageBucket: 'santefamille-c95e3.firebasestorage.app',
    iosBundleId: 'com.example.santeFamille',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClaOs2uPoOUREbK2H-1h7Ki6TAFIuHItc',
    appId: '1:861039145649:ios:d68facf4dfb3c1d07da890',
    messagingSenderId: '861039145649',
    projectId: 'santefamille-c95e3',
    storageBucket: 'santefamille-c95e3.firebasestorage.app',
    iosBundleId: 'com.example.santeFamille',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQB6FFtQgNepkkuXFTDrHN4oazvpmTa88',
    appId: '1:861039145649:web:7682d09cc1c3aad77da890',
    messagingSenderId: '861039145649',
    projectId: 'santefamille-c95e3',
    authDomain: 'santefamille-c95e3.firebaseapp.com',
    storageBucket: 'santefamille-c95e3.firebasestorage.app',
    measurementId: 'G-65BF3H0YPR',
  );
}
